 <!--Search Popup-->
 <div class="scroll-to-top scroll-to-target" data-target="html">
     <span class="fa fa-angle-double-up"></span>
 </div>



 <script src="js/jquery.js">
 </script>

 <script>
     (function(body) {
         'use strict';
         body.className = body.className.replace(/\btribe-no-js\b/, 'tribe-js');
     })(document.body);
 </script> <!--

        Theme: Newspaper by tagDiv 2016
        Version: 7.6 (rara)
        Deploy mode: deploy
        
        uid: 5e1ec026b110c
    -->
 <link href='/wp-content/plugins/js_composer/assets/lib/bower/flexslider/flexslider.min972f.css?ver=5.0.1' id='flexslider-css' media='all' rel='stylesheet' type='text/css'>
 <script src='/wp-content/themes/Fleboloji%20Dernegi%202017/js/tagdiv_themee87d.js?ver=7.6' type='text/javascript'>
 </script>
 <script src='/wp-includes/js/comment-reply.min8c23.js?ver=4.7.16' type='text/javascript'>
 </script>
 <script src='/wp-includes/js/wp-embed.min8c23.js?ver=4.7.16' type='text/javascript'>
 </script>
 <script src='/wp-content/plugins/js_composer/assets/js/dist/js_composer_front.min972f.js?ver=5.0.1' type='text/javascript'>
 </script>
 <script src='/wp-content/plugins/js_composer/assets/lib/bower/flexslider/jquery.flexslider-min972f.js?ver=5.0.1' type='text/javascript'>
 </script> <!-- JS generated by theme -->

 <script>
     (function() {
         var html_jquery_obj = jQuery('html');

         if (html_jquery_obj.length && (_jquery_obj.is('.ie8') || html_jquery_obj.is('.ie9'))) {

             var path = 'wp-content/themes/Fleboloji%20Dernegi%202017/style.css';

             jQuery.get(path, function(data) {

                 var str_split_separator = '#td_css_split_separator';
                 var arr_splits = data.split(str_split_separator);
                 var arr_length = arr_splits.length;

                 if (arr_length > 1) {

                     var dir_path = 'wp-content/themes/Fleboloji%20Dernegi%202017.html';
                     var splited_css = '';

                     for (var i = 0; i < arr_length; i++) {
                         if (i > 0) {
                             arr_splits[i] = str_split_separator + ' ' + arr_splits[i];
                         }
                         //jQuery('head').append('<style>' + arr_splits[i] + '<\/style>');

                         var formated_str = arr_splits[i].replace(/\surl\(\'(?!data\:)/gi, function regex_function(str) {
                             return ' url(\'' + dir_path + '/' + str.replace(/url\(\'/gi, '').replace(/^\s+|\s+$/gm, '');
                         });

                         splited_css += "<style>" + formated_str + "<\/style>";
                     }

                     var td_theme_css = jQuery('link#td-theme-css');

                     if (td_theme_css.length) {
                         td_theme_css.after(splited_css);
                     }
                 }
             });
         }
     })();
 </script><!-- Mirrored from www.flebolojidernegi.org.tr/ by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 15 Jan 2020 07:34:04 GMT -->